# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: weekly-menu.api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    mem_reservation: 500m
    cpu_count: 2
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI:  'mongodb://weekly-menu.db:27017'
    ports:
      - ${API_EXTERNAL_PORT}:${PORT}
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongodb/mongodb-community-server:latest
    container_name: weekly-menu.db
    restart: always
    mem_reservation: 300m
    cpu_count: 1
    ports:
      - ${DB_EXTERNAL_PORT}:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
