# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: 'weekly-menu'
      DATABASE_USER: 'admin'
      DATABASE_PASS: 'p@ssw0rd'
      DATABASE_URI:  'mongodb://database:27017'
    ports:
      - '5001:5001'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: # DATABASE_NAME
      MONGODB_INITDB_ROOT_PASSWORD: # DATABASE_USER
