# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: weekly-menu-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    mem_reservation: 500m
    cpu_count: 2
    environment:
      DATABASE_NAME: 'weekly-menu'
      DATABASE_USER: 'admin'
      DATABASE_PASS: 'p@ssw0rd'
      DATABASE_URI:  'mongodb://weekly-menu-db:27017'
    ports:
      - '5001:5001'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongodb/mongodb-community-server:latest
    container_name: weekly-menu-db
    restart: always
    mem_reservation: 300m
    cpu_count: 1
    ports:
      - '27017:27017'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: 'admin'
      MONGODB_INITDB_ROOT_PASSWORD: 'p@ssw0rd'
