name: API Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build
              run:
                docker compose build
            - name: Run
              run:
                docker compose up -d
