name: API Pipeline
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
    build-dev:
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        environment:
            name: Development
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Set up Environment
              shell: bash
              run: |
                echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" > .env.dev
              with:
                env:
                  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
            - name: Build
              run:
                docker compose --env-file .env.dev build
    build-prod:
        if: github.ref == 'refs/heads/master'
        environment:
            name: Production
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Set up Environment
              shell: bash
              run: |
                echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" > .env.prod
              with:
                env:
                  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
            - name: Build
              run:
                docker compose --env-file .env.prod build
    deploy-dev:
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        environment:
            name: Development
        needs: build-dev
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Set up Environment
              shell: bash
              run: |
                echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" > .env.prod
              with:
                env:
                  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
            - name: Build
              run:
                docker compose --env-file .env.dev up -d
    release:
        if: github.ref == 'refs/heads/master'
        environment:
            name: Production
        needs: [build-prod, deploy-dev]
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Set up Environment
              shell: bash
              run: |
                echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" > .env.prod
              with:
                env:
                  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
            - name: Build
              run:
                docker compose --env-file .env.prod up -d
