name: API Pipeline
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
    build:
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build
              run:
                docker compose build
    dev:
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        environment:
            name: Development
        needs: build
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                approvers: hcurtillet
                minimum-approvals: 1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build
              run:
                docker compose --env-file .env.dev up -d
    release:
        if: github.ref == 'refs/heads/master'
        environment:
            name: Production
        needs: dev
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build
              run:
                docker compose --env-file .env.prod up -d
